name: Model Training and Evaluation Pipeline

# Run this pipeline when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

# Define the job for model training and evaluation
jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the version of Python you want

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project's dependencies

    # Step 4: Run the model training and evaluation script
    - name: Train and Evaluate Model
      run: |
        python main.py  # Replace this with your actual script that trains the model

    # # Optionally: Save the trained model as an artifact (if needed)
    # - name: Upload Trained Model
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: trained-model
    #     path: path_to_your_trained_model.pkl  # Replace with your model file path
